#!/usr/bin/env bash

set -e


if [ -f /home/${USER}/${WORKSPACE}/install/setup.bash ]; then
    echo "source /home/${USER}/${WORKSPACE}/install/setup.bash" >> /home/${USER}/.bashrc;
fi

echo 'Startup completed.'
exec "$@"
