/**:
  ros__parameters:
    camera_matrix:
      fx: 699.4761
      fy: 697.332886
      cx: 644.753403
      cy: 509.920041
    camera_radar_transform:
      translation:
        x: 0.2
        y: 1.85
        z: 0.03
      rotation:
        x: 0.0305385
        y: 0.0
        z: 0.0
        w: 0.9995336

    image_height: 1024
    image_width: 1280

    input_radar_topic: "/radar/raw_points_T79"
